### ISSUE TITLE
Better code

### ISSUE THREAD

**Issue by WafaBenyettou** [DanaAmine/itclinique#1]
Indentation, there are no comments , better to use _ in naming classes rather than - ,Alt attribute should be more descriptive , better to define styling in the css files rather than inner styling , use semantic html f navbar thing

**Comment by DanaAmine** [comment]
It s not my work

**Comment by DanaAmine** [comment]
I am in sécurity team

**Comment by WafaBenyettou** [comment]
I believe that those kind of issues should be addressed and fixed by the technical team asap
